[package]
name = "reverie-engine"
version = "1.0.0"
authors = [""]

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
dbsdk-rs = "0.1.13"
hecs = "0.10.5"
ktx = "0.3.2"
lazy_static = "1.5.0"

[profile.dev]
opt-level = 0
debug = true
